apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- clusterrole.yaml
- clusterrolebinding.yaml
- deployment.yaml
- service.yaml
- serviceaccount.yaml

commonLabels:
  app.kubernetes.io/component: controller
  app.kubernetes.io/name: prometheus-operator

# namespace elided intentionally