apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- serviceaccount.yaml

commonLabels:
  app.kubernetes.io/component: alertmanager
  app.kubernetes.io/name: prometheus-operator

configMapGenerator:
  - # TODO

# namespace elided intentionally